# Generated by Django 5.2.8 on 2025-12-01 20:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("completed", models.BooleanField(default=False)),
                (
                    "dueDate",
                    models.BigIntegerField(
                        blank=True, help_text="Timestamp in milliseconds", null=True
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "createdAt",
                    models.BigIntegerField(help_text="Timestamp in milliseconds"),
                ),
            ],
        ),
    ]
